// Auto-generated by typescript_record_browser_flow from @playwright/mcp tool calls.
// Flow: positive-message
// Dev server: http://localhost:5173
import { test, expect } from '@playwright/test';

test('positive-message', async ({ page }) => {
  await page.goto('http://localhost:5173');
  await page.evaluate('() => document.body.innerText');
  await page.getByRole('textbox', { name: 'Type your message here...' }).fill('I love helping people and spreading kindness!');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText("Accepted!").first()).toBeVisible();
  await expect(page.getByText("The message expresses positive emotions and intentions").first()).toBeVisible();
});
